### ISSUE TITLE
Function `computefeaturecosts` not defined

### ISSUE THREAD

**Issue by jaromiru** [fnan/AdaptApprox#1]
Hello,

the code can't be run because the function `computefeaturecosts` is not defined at:
https://github.com/fnan/AdaptApprox/blob/ab0489a6ca934d0509c92c3146205aacd34c6213/ADAPT_GBRT/experiment_mbne.m#L85

**Comment by jaromiru** [comment]
I suppose this could do:
```matlab
function [featurecosts] = computefeaturecosts(lambda, defaultcosts, ensemble)

    alltrees = vertcat(ensemble{2}{:});
	
    if length(alltrees) > 0
		usedfeatures = unique(alltrees(:,1));
		usedfeatures = usedfeatures(usedfeatures>0);
		defaultcosts(usedfeatures) = 0;
	end
	featurecosts = lambda * defaultcosts;    
end
```

**Comment by fnan** [comment]
Thanks! I've added the file. Please let me know if you encounter any other problems!
